# LOGGING
logging:
  level: 
    root: info
    org.hibernate: error
    tech.espublico: info
  pattern:
    dateformat: dd-MM-yyyy HH:mm:ss
    console: 
  file: /tmp/ordersApplication.log

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./ordersAppDb
    username: sa 
    password: sa
    data:
    - classpath*:data.sql
    initialization-mode: always
  h2:
    console:
      enabled: true
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
  main:
    banner-mode: "off"
#### DB MYSQL
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/mydb?useSSL=false
#    username: root
#    password: admin
#    data:
#    - classpath*:data.sql
#    initialization-mode: always
#    
#  jpa:
#    database: MYSQL
#    show-sql: true
#    hibernate:
#      ddl-auto: update
    
#INPUT FILE
inputfile:
  columns:
    - Region
    - Country
    - Item Type
    - Sales Channel
    - Order Priority
    - Order Date
    - Order ID
    - Ship Date
    - Units Sold
    - Unit Price
    - Unit Cost
    - Total Revenue
    - Total Cost
    - Total Profit
    

      

        

